"""OBJ export for SMPL body meshes.

Exports vertices and triangulated faces to Wavefront OBJ format without
external dependencies beyond numpy.  Useful for generating collision-proxy
meshes consumed by Blender Cloth simulation.

Usage::

    from wearme.io.obj_export import body_to_obj
    from wearme.body.smpl_bridge import load_model_data
    from wearme.body.body_params import BodyParameters

    model = load_model_data("neutral")
    params = BodyParameters(height_m=1.75)
    path = body_to_obj(params, model, "output/body.obj")
"""

from __future__ import annotations

import logging
from pathlib import Path

import numpy as np

logger = logging.getLogger(__name__)


# ── Internal helpers ────────────────────────────────────────────────────────────


def _scale_to_height(
    vertices: np.ndarray,
    height_m: float | None,
) -> np.ndarray:
    """Uniformly scale *vertices* so the Y-axis span equals *height_m*.

    A no-op when *height_m* is ``None`` or the mesh has zero extent.

    Args:
        vertices: Shape ``(N, 3)``.
        height_m: Target standing height in metres.

    Returns:
        Scaled array (copy).
    """
    if height_m is None or height_m <= 0:
        return vertices.copy()

    y_min = float(vertices[:, 1].min())
    y_max = float(vertices[:, 1].max())
    mesh_height = y_max - y_min
    if mesh_height <= 0:
        return vertices.copy()

    scale = height_m / mesh_height
    logger.debug("Scaling mesh to height_m=%.3f (factor %.4f)", height_m, scale)
    return vertices * scale


# ── Low-level export (raw arrays) ──────────────────────────────────────────────


def export_obj(
    vertices: np.ndarray,
    faces: np.ndarray,
    path: Path | str,
    *,
    height_m: float | None = None,
    comment: str = "Generated by WEARME",
) -> Path:
    """Write vertex/face arrays to a Wavefront OBJ file.

    The file uses 1-based vertex indices as required by the OBJ spec.
    No mtl/material references are written.

    Args:
        vertices: Vertex coordinates. Shape ``(N, 3)``, in metres.
        faces: Triangle face indices. Shape ``(F, 3)``, 0-based.
        path: Destination file path.  Parent directories are created
            automatically.
        height_m: Optional height rescaling before export.
        comment: Comment line written at the top of the file.

    Returns:
        Resolved path of the written file.
    """
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)

    verts = _scale_to_height(vertices, height_m)

    lines: list[str] = []
    if comment:
        lines.append(f"# {comment}")
    lines.append(f"# vertices={len(verts)}  faces={len(faces)}")
    lines.append("")

    for v in verts:
        lines.append(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}")
    lines.append("")

    # OBJ face indices are 1-based
    for f in faces:
        lines.append(f"f {f[0] + 1} {f[1] + 1} {f[2] + 1}")

    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info("OBJ written to %s (%d verts, %d faces)", out, len(verts), len(faces))
    return out


# ── High-level export (BodyParameters) ─────────────────────────────────────────


def body_to_obj(
    params: object,
    model_data: object,
    path: Path | str,
    *,
    height_m: float | None = None,
) -> Path:
    """Generate and export an OBJ from a :class:`~wearme.body.body_params.BodyParameters` instance.

    Args:
        params: Body shape and pose parameters
            (:class:`~wearme.body.body_params.BodyParameters`).
        model_data: Loaded SMPL model data
            (:class:`~wearme.body.smpl_bridge.SMPLModelData`).
        path: Destination OBJ file path.
        height_m: Override target height in metres.
            Defaults to ``params.height_m``.

    Returns:
        Resolved path of the written OBJ file.
    """
    from wearme.body.smpl_bridge import generate_vertices  # noqa: PLC0415

    vertices = generate_vertices(params, model_data)  # type: ignore[arg-type]
    target_height = height_m if height_m is not None else params.height_m  # type: ignore[attr-defined]
    return export_obj(vertices, model_data.faces, path, height_m=target_height)  # type: ignore[attr-defined]
